# Generated by Django 4.0.4 on 2022-10-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DY', 'Day'), ('WY', 'Week'), ('MY', 'Month'), ('6Y', '6 Months'), ('YY', 'Year')], max_length=2)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Subscription Types',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.subject')),
                ('subscription_types', models.ManyToManyField(to='questionnaire.subscriptiontypes')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
