# Generated by Django 4.0.4 on 2022-10-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_levels_options_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubscription',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='expiryHours',
            field=models.IntegerField(default=24),
        ),
    ]
