# Generated by Django 4.0.4 on 2022-10-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_studentsubscription_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubscription',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
