# Generated by Django 4.0.4 on 2022-10-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontypes',
            name='title',
            field=models.CharField(choices=[('FR', 'Free Trial'), ('DY', 'Daily'), ('WY', 'Weekly'), ('MY', 'Monthly'), ('6Y', '6 Months'), ('YY', 'Yearly')], max_length=2),
        ),
    ]
