# Generated by Django 4.0.4 on 2022-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=2048)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
